-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["Happy_cat"] = {
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -30, 11  ,  -27.5, 23.5  ,  -37, 17  ,  -37.5, 12.5  }
                    } ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   31, 8  ,  31.5, 11.5  ,  28, 14  ,  23, 16  ,  17, 16  ,  5, 8  ,  20, 6  ,  28, 6  }
                    } ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   7, 20  ,  5, 8  ,  17, 16  }
                    } ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -28.5, 52.5  ,  -26.5, 49.5  ,  -18, 50  ,  -23.5, 55.5  ,  -28, 55  }
                    } ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -25.5, 5.5  ,  0.5, 3.5  ,  1.5, 27.5  ,  1.5, 39.5  ,  -18, 50  ,  -27.5, 23.5  ,  -30, 11  }
                    } ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -27.5, 23.5  ,  -18, 50  ,  -26.5, 49.5  }
                    } ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -0.5, 44.5  ,  -1.5, 55.5  ,  -5, 56  ,  -11, 50  }
                    } ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2, -13  ,  0.5, 3.5  ,  -5, -10  ,  -1, -13  }
                    } ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -20, -12  ,  -5, -10  ,  0.5, 3.5  ,  -25.5, 5.5  ,  -25.5, 0.5  }
                    } ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   4, 23  ,  0.5, 3.5  ,  5, 8  ,  7, 20  }
                    } ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -11, 50  ,  -18, 50  ,  1.5, 39.5  ,  -0.5, 44.5  }
                    } ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -27, -15  ,  -26, -15  ,  -20, -12  ,  -28.5, -7.5  ,  -28.5, -14.5  }
                    } ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -25.5, 0.5  ,  -28.5, -7.5  ,  -20, -12  }
                    } ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   4, 23  ,  1.5, 27.5  ,  0.5, 3.5  }
                    }
		}
		, 
		["cat2"] = {
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   56.5, -38  ,  55.5, -34  ,  37.5, -2  ,  27, -28.5  ,  52, -40.5  ,  55, -40.5  }
                    } ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -54, -44.5  ,  -55.5, -39  ,  -56.5, -45  }
                    } ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -49.5, 31  ,  -49.5, 9  ,  -48.5, 1  ,  -43.5, -13  ,  -14, 39.5  ,  -44, 41.5  }
                    } ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   37.5, -2  ,  16, -28.5  ,  27, -28.5  }
                    } ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -43.5, -13  ,  -5, -29.5  ,  16, -28.5  ,  37.5, -2  ,  41.5, 29  ,  12, 41.5  ,  -14, 39.5  }
                    } ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   38.5, 36  ,  12, 41.5  ,  41.5, 29  ,  40.5, 34  }
                    } ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   16, -28.5  ,  -5, -29.5  ,  -1, -31.5  ,  11, -31.5  }
                    } ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -53, -44.5  ,  -29, -30.5  ,  -43.5, -18  ,  -55.5, -39  ,  -54, -44.5  }
                    } ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -43.5, -18  ,  -29, -30.5  ,  -10, -31.5  ,  -5, -29.5  ,  -43.5, -13  }
                    } ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   41.5, 40  ,  12, 41.5  ,  38.5, 36  }
                    } ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   39.5, 12  ,  37.5, -2  ,  40.5, 9  }
                    }
		}
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end

	function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
	end
	
	return physics;
end

return M

